export const projects = [
  {
    img: "https://raw.githubusercontent.com/Sayli555/project-images/master/E-shop.png",
    title: "E-Shop Clone",
    des: "The E-Shop website is a clone project developed during a Full Stack development bootcamp at Masai School. It focuses on e-commerce for clothing and accessories, serving as an individual project to showcase the skills acquired during the program.",
    live: "https://e-shop-ruby.vercel.app/",
    gitHub: "https://github.com/Sayli555/e-shop",
    technologies: ["React", "Redux", "HTML","Javascript","CSS"],
  },
  // {
  //   img: "https://user-images.githubusercontent.com/97591028/180641416-56175994-d677-4ca7-9a16-f4063fa30ed0.png",
  //   title: "HubSpot Clone",
  //   des: "This is the clone of HubSpot website. HubSpot is a marketing , sales and customer service platform that helps companies grow better.. This is our team collaboration project at Full Stack-development bootcamp in Masai School.",
  //   demo: "",
  //   live: "https://leafy-moxie-ee6b4e.netlify.app/",
  //   gitHub: "https://github.com/optimizershivam/Hubspot-clone",
  //   technologies: ["React", "Redux", "Chakra UI","Javascript","CSS"],
  // },
  {
    img: "https://github.com/sahilshekh/project-photos/blob/master/photos/jio-mart.png?raw=true",
    title: "JioMart Clone",
    des: "The web application is a collaborative project undertaken during a Full Stack development bootcamp at Masai School, designed to mimic the JioMart website. It facilitates the online purchase of grocery and daily-need products.",
    demo: "",
    live: "https://jio-mart-clone.vercel.app/",
    gitHub: "https://github.com/jibi966/JioMart-clone",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    img: "https://github.com/sahilshekh/project-photos/blob/master/photos/west-side.png?raw=true",
    title: "Westside-ecommerce-Clone",
    des: "This collaborative project at Masai School's Full Stack development bootcamp replicates Westside Shopping's e-commerce platform for clothing. Explore a diverse range of apparel selections with a user-friendly interface and seamless shopping experience.",
    demo: "",
    live: "https://westside-ecommerce-clone.vercel.app/",
    gitHub: "https://github.com/mdalishanali/Westside-ecommerce-Clone",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
    ],
  },
  {
    img: "https://github.com/Sayli555/project-images/blob/master/tictacktow.png?raw=true",
    title: "Tic-Tac-Tow Game",
    des: "Tic-Tac-Toe is a classic 3x3 grid game where players take turns marking X and O, aiming to create a line of their symbol horizontally, vertically, or diagonally to win. The first player to achieve this goal is the winner.",
    demo: "",
    live: "https://tic-tac-tow.vercel.app/",
    gitHub: "https://github.com/Sayli555/tic-tac-tow",
    technologies: ["React","Hooks", "CSS"],
  },
  {
    img: "https://github.com/Sayli555/project-images/blob/master/weatherapp.png?raw=true",
    title: "Weather-app",
    des: "The Weather app delivers real-time weather updates for a specified city, offering details on temperature, humidity, and wind speed. Users can access forecasts, radar maps, and essential information to plan their activities.",
    demo: "",
    live: "https://weather-app424.netlify.app/",
    gitHub: "https://github.com/Sayli555/weather-app",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    img: "https://github.com/Sayli555/project-images/blob/master/googletimer.png?raw=true",
    title: "Google Timer",
    des: "Google Timer is a user-friendly online tool that allows individuals to set and monitor countdowns effortlessly. With its intuitive interface, users can easily input their desired time, helping them stay organized and focused on tasks or activities.",
    demo: "",
    live: "https://google-timer-three.vercel.app/",
    gitHub: "https://github.com/Sayli555/google_timer",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    img: "https://github.com/sahilshekh/project-photos/blob/master/photos/purplle.png?raw=true",
    title: "Purple-Clone",
    des: "The purple-skincare & makeup website clone offers a seamless shopping experience for skincare and makeup enthusiasts. Developed as a solo project at Masai School's Full Stack development bootcamp, it delivers a user-friendly interface for purchasing high-quality beauty products.",
    demo: "",
    live: "https://inspiring-aryabhata-5a6301.netlify.app/",
    gitHub: "https://github.com/Sayli555/purple-clone",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  // {
  //   img: "https://miro.medium.com/max/1400/0*_a0kLpcnLpnrWlHB.png",
  //   title: "Credo Clone",
  //   des: "This is the clone of Credo website. A web application to buy skincare and makeup products. This is our team collaboration project at Full Stack-development bootcamp in Masai School.",
  //   demo: "",
  //   live: "https://westside-ecommerce-clone.vercel.app/",
  //   gitHub: "https://github.com/Sayli555/credo-clone/",
  //   technologies: ["HTML", "CSS", "JavaScript","NodeJS","ExpressJS","MongoDB"],
  // },
];
